Update train_and_evaluate_using_ray.md
I get Error:
ValueError: Missing column provided to 'parse_dates': 'Datetime'
-> changed index=True to get 'Datetime'